# Use mv_data_split() to obtain train and test subsets of data

### Obtaining train-test splits of multi-view data
This example illustrates how we can use mv_data_split to quickly obtain training and testing subsets of multi-view data.

In [1]:
# Import relevant packages
from mvlearn.preprocessing import mv_data_split
import numpy as np

# Setting random seed
RANDOM_STATE = 10
np.random.seed(RANDOM_STATE)

In [2]:
# Creating multi-view data with 3 views
data = np.arange(18).reshape((3, 3, 2))
print(data)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [3]:
# Splitting data into training and testing sets
train_Xs, test_Xs = mv_data_split(data, test_size=0.33,
                                  random_state=RANDOM_STATE)
# Printing train set
print('Train Set')
for X in train_Xs:
    print(X, '\n')
    
# Printing test set
print('\nTest Set')
for X in test_Xs:
    print(X, '\n')

Train Set
[[4 5]
 [2 3]] 

[[10 11]
 [ 8  9]] 

[[16 17]
 [14 15]] 


Test Set
[[0 1]] 

[[6 7]] 

[[12 13]] 

